<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-10-20 06:16
=======
# Generated by Django 4.1.2 on 2022-10-20 07:20
>>>>>>> 8df2fe506a4b2a5d726b344b156ad019f5df4165

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
