# Generated by Django 4.1.2 on 2022-10-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_imagemodel_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
