# Generated by Django 4.1.2 on 2022-10-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_table'),
        ('user', '0003_remove_user_image'),
    ]

    operations = [
    ]
