# Generated by Django 4.1.2 on 2022-10-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_merge_0002_alter_user_table_0003_remove_user_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagemodel',
            table='image_model',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
